-- =============================================
-- STEP 1: RESET & SETUP DATABASE
-- =============================================
DROP DATABASE IF EXISTS library_system_sem3;
CREATE DATABASE library_system_sem3;
USE library_system_sem3;

-- =============================================
-- STEP 2: CREATE TABLES
-- =============================================
CREATE TABLE books (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    publication_year INT NOT NULL,
    shelf_number VARCHAR(20) NOT NULL,
    is_available BOOLEAN DEFAULT TRUE
);

CREATE TABLE members (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE,
    type VARCHAR(20) DEFAULT 'Student'
);

CREATE TABLE issue_records (
    id INT PRIMARY KEY AUTO_INCREMENT,
    book_id INT,
    member_id INT,
    issue_date DATE,
    due_date DATE,
    return_date DATE,
    fine_amount DECIMAL(10,2) DEFAULT 0.0,
    status VARCHAR(20) DEFAULT 'ISSUED', 
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE
);

-- =============================================
-- STEP 3: INSERT 25 MEMBERS
-- =============================================
INSERT INTO members (name, email, type) VALUES 
('Zainab Bibi', 'zainab.b@uni.edu', 'Student'),
('Bilal Ahmed', 'bilal.a@uni.edu', 'Student'),
('Ayesha Malik', 'ayesha.m@uni.edu', 'Student'),
('Usman Gondal', 'usman.g@uni.edu', 'Student'),
('Fatima Noor', 'fatima.n@uni.edu', 'Student'),
('Hassan Raza', 'hassan.r@uni.edu', 'Student'),
('Sadia Parveen', 'sadia.p@uni.edu', 'Student'),
('Omar Farooq', 'omar.f@uni.edu', 'Student'),
('Khadija Tul Kubra', 'khadija.k@uni.edu', 'Student'),
('Mustafa Kamal', 'mustafa.k@uni.edu', 'Student'),
('Hira Mani', 'hira.m@uni.edu', 'Student'),
('Fahad Mustafa', 'fahad.m@uni.edu', 'Student'),
('Sana Javed', 'sana.j@uni.edu', 'Faculty'),
('Ahsan Khan', 'ahsan.k@uni.edu', 'Faculty'),
('Mahira Khan', 'mahira.k@uni.edu', 'Student'),
('Humayun Saeed', 'humayun.s@uni.edu', 'Student'),
('Yumna Zaidi', 'yumna.z@uni.edu', 'Student'),
('Wahaj Ali', 'wahaj.a@uni.edu', 'Student'),
('Kinza Hashmi', 'kinza.h@uni.edu', 'Student'),
('Danish Taimoor', 'danish.t@uni.edu', 'Student'),
('Ayeza Khan', 'ayeza.k@uni.edu', 'Student'),
('Hamza Ali Abbasi', 'hamza.a@uni.edu', 'Student'),
('Sajal Aly', 'sajal.a@uni.edu', 'Student'),
('Ahad Raza Mir', 'ahad.r@uni.edu', 'Student'),
('Iqra Aziz', 'iqra.a@uni.edu', 'Student');

-- =============================================
-- STEP 4: INSERT 200 BOOKS
-- =============================================
INSERT INTO books (title, author, publication_year, shelf_number) VALUES
-- Computer Science
('Clean Code', 'Robert C. Martin', 2008, 'CS-01'),
('The Pragmatic Programmer', 'Andrew Hunt', 1999, 'CS-02'),
('Design Patterns', 'Erich Gamma', 1994, 'CS-03'),
('Introduction to Algorithms', 'Thomas H. Cormen', 2009, 'CS-04'),
('Cracking the Coding Interview', 'Gayle Laakmann', 2015, 'CS-05'),
('Head First Java', 'Kathy Sierra', 2005, 'CS-06'),
('Effective Java', 'Joshua Bloch', 2018, 'CS-07'),
('Java Concurrency in Practice', 'Brian Goetz', 2006, 'CS-08'),
('Refactoring', 'Martin Fowler', 2018, 'CS-09'),
('Code Complete', 'Steve McConnell', 2004, 'CS-10'),
('The Mythical Man-Month', 'Fred Brooks', 1975, 'CS-11'),
('You Don’t Know JS', 'Kyle Simpson', 2015, 'CS-12'),
('Eloquent JavaScript', 'Marijn Haverbeke', 2018, 'CS-13'),
('Python Crash Course', 'Eric Matthes', 2019, 'CS-14'),
('Automate the Boring Stuff with Python', 'Al Sweigart', 2015, 'CS-15'),
('Fluent Python', 'Luciano Ramalho', 2015, 'CS-16'),
('Learning Python', 'Mark Lutz', 2013, 'CS-17'),
('Grokking Algorithms', 'Aditya Bhargava', 2016, 'CS-18'),
('Structure and Interpretation of Computer Programs', 'Harold Abelson', 1996, 'CS-19'),
('Compilers: Principles, Techniques, and Tools', 'Alfred Aho', 2006, 'CS-20'),
('Operating System Concepts', 'Abraham Silberschatz', 2018, 'CS-21'),
('Computer Networking: A Top-Down Approach', 'Kurose & Ross', 2020, 'CS-22'),
('Database System Concepts', 'Abraham Silberschatz', 2019, 'CS-23'),
('Artificial Intelligence: A Modern Approach', 'Stuart Russell', 2020, 'CS-24'),
('Deep Learning', 'Ian Goodfellow', 2016, 'CS-25'),
('Hands-On Machine Learning', 'Aurélien Géron', 2019, 'CS-26'),
('Pattern Recognition and Machine Learning', 'Christopher Bishop', 2006, 'CS-27'),
('The Art of Computer Programming, Vol 1', 'Donald Knuth', 1968, 'CS-28'),
('The Art of Computer Programming, Vol 2', 'Donald Knuth', 1969, 'CS-29'),
('The Art of Computer Programming, Vol 3', 'Donald Knuth', 1973, 'CS-30'),
('C Programming Language', 'Brian Kernighan', 1988, 'CS-31'),
('C++ Primer', 'Stanley B. Lippman', 2012, 'CS-32'),
('The C++ Programming Language', 'Bjarne Stroustrup', 2013, 'CS-33'),
('Effective Modern C++', 'Scott Meyers', 2014, 'CS-34'),
('Rust Programming Language', 'Steve Klabnik', 2018, 'CS-35'),
('Programming in Scala', 'Martin Odersky', 2016, 'CS-36'),
('Haskell Programming from First Principles', 'Christopher Allen', 2016, 'CS-37'),
('Real World OCaml', 'Yaron Minsky', 2013, 'CS-38'),
('Learning SQL', 'Alan Beaulieu', 2020, 'CS-39'),
('SQL Performance Explained', 'Markus Winand', 2012, 'CS-40'),
('High Performance MySQL', 'Baron Schwartz', 2012, 'CS-41'),
('Designing Data-Intensive Applications', 'Martin Kleppmann', 2017, 'CS-42'),
('Building Microservices', 'Sam Newman', 2015, 'CS-43'),
('Domain-Driven Design', 'Eric Evans', 2003, 'CS-44'),
('Implementing Domain-Driven Design', 'Vaughn Vernon', 2013, 'CS-45'),
('Continuous Delivery', 'Jez Humble', 2010, 'CS-46'),
('The Phoenix Project', 'Gene Kim', 2013, 'CS-47'),
('The DevOps Handbook', 'Gene Kim', 2016, 'CS-48'),
('Site Reliability Engineering', 'Betsy Beyer', 2016, 'CS-49'),
('Kubernetes Up and Running', 'Kelsey Hightower', 2019, 'CS-50'),
('Docker Deep Dive', 'Nigel Poulton', 2020, 'CS-51'),
('Linux Bible', 'Christopher Negus', 2020, 'CS-52'),
('How Linux Works', 'Brian Ward', 2014, 'CS-53'),
('Unix Network Programming', 'W. Richard Stevens', 1990, 'CS-54'),
('Advanced Programming in the UNIX Environment', 'W. Richard Stevens', 1992, 'CS-55'),
('TCP/IP Illustrated', 'W. Richard Stevens', 1994, 'CS-56'),
('Hacking: The Art of Exploitation', 'Jon Erickson', 2008, 'CS-57'),
('The Web Application Hacker’s Handbook', 'Dafydd Stuttard', 2011, 'CS-58'),
('Black Hat Python', 'Justin Seitz', 2014, 'CS-59'),
('Violent Python', 'TJ OConnor', 2012, 'CS-60'),
('Metasploit: The Penetration Tester’s Guide', 'David Kennedy', 2011, 'CS-61'),
('Cryptography and Network Security', 'William Stallings', 2016, 'CS-62'),
('Applied Cryptography', 'Bruce Schneier', 1996, 'CS-63'),
('Security Engineering', 'Ross Anderson', 2020, 'CS-64'),
('Practical Malware Analysis', 'Michael Sikorski', 2012, 'CS-65'),
('The Shellcoder’s Handbook', 'Chris Anley', 2007, 'CS-66'),
('Game Programming Patterns', 'Robert Nystrom', 2014, 'CS-67'),
('Unity in Action', 'Joseph Hocking', 2018, 'CS-68'),
('Unreal Engine 4 Game Development', 'Satheesh PV', 2016, 'CS-69'),
('Foundations of Game Engine Development', 'Eric Lengyel', 2016, 'CS-70'),
('Real-Time Rendering', 'Tomas Akenine-Möller', 2018, 'CS-71'),
('Computer Graphics: Principles and Practice', 'John Hughes', 2013, 'CS-72'),
('Digital Image Processing', 'Rafael Gonzalez', 2018, 'CS-73'),
('Computer Vision: Algorithms and Applications', 'Richard Szeliski', 2010, 'CS-74'),
('Multiple View Geometry in Computer Vision', 'Richard Hartley', 2004, 'CS-75'),
('Probabilistic Robotics', 'Sebastian Thrun', 2005, 'CS-76'),
('Introduction to Robotics', 'John Craig', 2017, 'CS-77'),
('Speech and Language Processing', 'Daniel Jurafsky', 2020, 'CS-78'),
('Natural Language Processing with Python', 'Steven Bird', 2009, 'CS-79'),
('Reinforcement Learning: An Introduction', 'Richard Sutton', 2018, 'CS-80'),
-- Math & Physics
('Calculus', 'James Stewart', 2015, 'MA-01'),
('Linear Algebra and Its Applications', 'Gilbert Strang', 2016, 'MA-02'),
('Introduction to Probability', 'Dimitri Bertsekas', 2008, 'MA-03'),
('Concrete Mathematics', 'Ronald Graham', 1994, 'MA-04'),
('Discrete Mathematics and Its Applications', 'Kenneth Rosen', 2018, 'MA-05'),
('The Feynman Lectures on Physics Vol 1', 'Richard Feynman', 1964, 'PH-01'),
('The Feynman Lectures on Physics Vol 2', 'Richard Feynman', 1964, 'PH-02'),
('The Feynman Lectures on Physics Vol 3', 'Richard Feynman', 1964, 'PH-03'),
('A Brief History of Time', 'Stephen Hawking', 1988, 'PH-04'),
('Cosmos', 'Carl Sagan', 1980, 'PH-05'),
('The Elegant Universe', 'Brian Greene', 1999, 'PH-06'),
('Relativity: The Special and General Theory', 'Albert Einstein', 1916, 'PH-07'),
('Quantum Mechanics: The Theoretical Minimum', 'Leonard Susskind', 2014, 'PH-08'),
('Principles of Mathematical Analysis', 'Walter Rudin', 1976, 'MA-06'),
('Topology', 'James Munkres', 2000, 'MA-07'),
('Abstract Algebra', 'David Dummit', 2003, 'MA-08'),
('Number Theory', 'George Andrews', 1994, 'MA-09'),
('Geometry Revisited', 'H.S.M. Coxeter', 1967, 'MA-10'),
('University Physics', 'Hugh Young', 2019, 'PH-09'),
('Fundamentals of Physics', 'David Halliday', 2013, 'PH-10'),
-- Fiction & Lit
('To Kill a Mockingbird', 'Harper Lee', 1960, 'LIT-01'),
('1984', 'George Orwell', 1949, 'LIT-02'),
('Pride and Prejudice', 'Jane Austen', 1813, 'LIT-03'),
('The Great Gatsby', 'F. Scott Fitzgerald', 1925, 'LIT-04'),
('Moby Dick', 'Herman Melville', 1851, 'LIT-05'),
('War and Peace', 'Leo Tolstoy', 1869, 'LIT-06'),
('The Catcher in the Rye', 'J.D. Salinger', 1951, 'LIT-07'),
('The Hobbit', 'J.R.R. Tolkien', 1937, 'LIT-08'),
('The Fellowship of the Ring', 'J.R.R. Tolkien', 1954, 'LIT-09'),
('The Two Towers', 'J.R.R. Tolkien', 1954, 'LIT-10'),
('The Return of the King', 'J.R.R. Tolkien', 1955, 'LIT-11'),
('Fahrenheit 451', 'Ray Bradbury', 1953, 'LIT-12'),
('Jane Eyre', 'Charlotte Bronte', 1847, 'LIT-13'),
('Wuthering Heights', 'Emily Bronte', 1847, 'LIT-14'),
('Animal Farm', 'George Orwell', 1945, 'LIT-15'),
('Lord of the Flies', 'William Golding', 1954, 'LIT-16'),
('Brave New World', 'Aldous Huxley', 1932, 'LIT-17'),
('The Chronicles of Narnia', 'C.S. Lewis', 1950, 'LIT-18'),
('The Alchemist', 'Paulo Coelho', 1988, 'LIT-19'),
('The Kite Runner', 'Khaled Hosseini', 2003, 'LIT-20'),
('A Thousand Splendid Suns', 'Khaled Hosseini', 2007, 'LIT-21'),
('Life of Pi', 'Yann Martel', 2001, 'LIT-22'),
('The Book Thief', 'Markus Zusak', 2005, 'LIT-23'),
('Memoirs of a Geisha', 'Arthur Golden', 1997, 'LIT-24'),
('The Hunger Games', 'Suzanne Collins', 2008, 'LIT-25'),
('Catching Fire', 'Suzanne Collins', 2009, 'LIT-26'),
('Mockingjay', 'Suzanne Collins', 2010, 'LIT-27'),
('Harry Potter and the Sorcerer’s Stone', 'J.K. Rowling', 1997, 'LIT-28'),
('Harry Potter and the Chamber of Secrets', 'J.K. Rowling', 1998, 'LIT-29'),
('Harry Potter and the Prisoner of Azkaban', 'J.K. Rowling', 1999, 'LIT-30'),
('Harry Potter and the Goblet of Fire', 'J.K. Rowling', 2000, 'LIT-31'),
('Harry Potter and the Order of the Phoenix', 'J.K. Rowling', 2003, 'LIT-32'),
('Harry Potter and the Half-Blood Prince', 'J.K. Rowling', 2005, 'LIT-33'),
('Harry Potter and the Deathly Hallows', 'J.K. Rowling', 2007, 'LIT-34'),
('A Game of Thrones', 'George R.R. Martin', 1996, 'LIT-35'),
('A Clash of Kings', 'George R.R. Martin', 1998, 'LIT-36'),
('A Storm of Swords', 'George R.R. Martin', 2000, 'LIT-37'),
('A Feast for Crows', 'George R.R. Martin', 2005, 'LIT-38'),
('A Dance with Dragons', 'George R.R. Martin', 2011, 'LIT-39'),
('Dune', 'Frank Herbert', 1965, 'LIT-40'),
('Dune Messiah', 'Frank Herbert', 1969, 'LIT-41'),
('Children of Dune', 'Frank Herbert', 1976, 'LIT-42'),
('Foundation', 'Isaac Asimov', 1951, 'LIT-43'),
('Foundation and Empire', 'Isaac Asimov', 1952, 'LIT-44'),
('Second Foundation', 'Isaac Asimov', 1953, 'LIT-45'),
('I, Robot', 'Isaac Asimov', 1950, 'LIT-46'),
('Neuromancer', 'William Gibson', 1984, 'LIT-47'),
('Snow Crash', 'Neal Stephenson', 1992, 'LIT-48'),
('Ready Player One', 'Ernest Cline', 2011, 'LIT-49'),
('The Martian', 'Andy Weir', 2011, 'LIT-50'),
-- General Knowledge & History
('Sapiens: A Brief History of Humankind', 'Yuval Noah Harari', 2011, 'HIS-01'),
('Homo Deus', 'Yuval Noah Harari', 2015, 'HIS-02'),
('21 Lessons for the 21st Century', 'Yuval Noah Harari', 2018, 'HIS-03'),
('Guns, Germs, and Steel', 'Jared Diamond', 1997, 'HIS-04'),
('Thinking, Fast and Slow', 'Daniel Kahneman', 2011, 'PSY-01'),
('Atomic Habits', 'James Clear', 2018, 'SELF-01'),
('The Power of Habit', 'Charles Duhigg', 2012, 'SELF-02'),
('Deep Work', 'Cal Newport', 2016, 'SELF-03'),
('Digital Minimalism', 'Cal Newport', 2019, 'SELF-04'),
('Rich Dad Poor Dad', 'Robert Kiyosaki', 1997, 'FIN-01'),
('The Intelligent Investor', 'Benjamin Graham', 1949, 'FIN-02'),
('Think and Grow Rich', 'Napoleon Hill', 1937, 'FIN-03'),
('Principles', 'Ray Dalio', 2017, 'FIN-04'),
('Zero to One', 'Peter Thiel', 2014, 'BUS-01'),
('The Lean Startup', 'Eric Ries', 2011, 'BUS-02'),
('Good to Great', 'Jim Collins', 2001, 'BUS-03'),
('Start with Why', 'Simon Sinek', 2009, 'BUS-04'),
('Leaders Eat Last', 'Simon Sinek', 2014, 'BUS-05'),
('Extreme Ownership', 'Jocko Willink', 2015, 'BUS-06'),
('Can’t Hurt Me', 'David Goggins', 2018, 'BIO-01'),
('Becoming', 'Michelle Obama', 2018, 'BIO-02'),
('Steve Jobs', 'Walter Isaacson', 2011, 'BIO-03'),
('Elon Musk', 'Ashlee Vance', 2015, 'BIO-04'),
('Wings of Fire', 'A.P.J. Abdul Kalam', 1999, 'BIO-05'),
('Long Walk to Freedom', 'Nelson Mandela', 1994, 'BIO-06'),
('The Diary of a Young Girl', 'Anne Frank', 1947, 'BIO-07'),
('Meditation', 'Marcus Aurelius', 180, 'PHI-01'),
('Beyond Good and Evil', 'Friedrich Nietzsche', 1886, 'PHI-02'),
('The Republic', 'Plato', -375, 'PHI-03'),
('Critique of Pure Reason', 'Immanuel Kant', 1781, 'PHI-04'),
('The Prince', 'Niccolo Machiavelli', 1532, 'PHI-05'),
('Art of War', 'Sun Tzu', -500, 'PHI-06'),
('Tao Te Ching', 'Laozi', -400, 'PHI-07'),
('Man’s Search for Meaning', 'Viktor Frankl', 1946, 'PSY-02'),
('The Tipping Point', 'Malcolm Gladwell', 2000, 'SOC-01'),
('Outliers', 'Malcolm Gladwell', 2008, 'SOC-02'),
('Blink', 'Malcolm Gladwell', 2005, 'SOC-03'),
('Quiet', 'Susan Cain', 2012, 'PSY-03'),
('Influence', 'Robert Cialdini', 1984, 'PSY-04'),
('Predictably Irrational', 'Dan Ariely', 2008, 'PSY-05'),
('Freakonomics', 'Steven Levitt', 2005, 'ECO-01'),
('Nudge', 'Richard Thaler', 2008, 'ECO-02'),
('Capital in the Twenty-First Century', 'Thomas Piketty', 2013, 'ECO-03'),
('The Wealth of Nations', 'Adam Smith', 1776, 'ECO-04'),
('Das Kapital', 'Karl Marx', 1867, 'ECO-05'),
('A History of the World in 6 Glasses', 'Tom Standage', 2005, 'HIS-05'),
('Salt: A World History', 'Mark Kurlansky', 2002, 'HIS-06'),
('Cod: A Biography of the Fish', 'Mark Kurlansky', 1997, 'HIS-07'),
('Longitude', 'Dava Sobel', 1995, 'HIS-08'),
('The Silk Roads', 'Peter Frankopan', 2015, 'HIS-09'),
('Genghis Khan and the Making of the Modern World', 'Jack Weatherford', 2004, 'HIS-10'),
('1776', 'David McCullough', 2005, 'HIS-11'),
('Team of Rivals', 'Doris Kearns Goodwin', 2005, 'HIS-12'),
('The Rise and Fall of the Third Reich', 'William Shirer', 1960, 'HIS-13'),
('Stalin: The Court of the Red Tsar', 'Simon Sebag Montefiore', 2003, 'HIS-14'),
('Mao: The Unknown Story', 'Jung Chang', 2005, 'HIS-15'),
('Wild Swans', 'Jung Chang', 1991, 'HIS-16'),
('Midnight’s Children', 'Salman Rushdie', 1981, 'LIT-51'),
('The God of Small Things', 'Arundhati Roy', 1997, 'LIT-52'),
('A Suitable Boy', 'Vikram Seth', 1993, 'LIT-53'),
('Train to Pakistan', 'Khushwant Singh', 1956, 'LIT-54'),
('In the Line of Fire', 'Pervez Musharraf', 2006, 'BIO-08'),
('My Feudal Lord', 'Tehmina Durrani', 1991, 'BIO-09'),
('Jinnah of Pakistan', 'Stanley Wolpert', 1984, 'BIO-10'),
('Pakistan: A Hard Country', 'Anatol Lieven', 2011, 'HIS-17'),
('The Indus Saga', 'Aitzaz Ahsan', 1996, 'HIS-18'),
('Murder on the Orient Express', 'Agatha Christie', 1934, 'LIT-55'),
('And Then There Were None', 'Agatha Christie', 1939, 'LIT-56'),
('The Murder of Roger Ackroyd', 'Agatha Christie', 1926, 'LIT-57'),
('Sherlock Holmes: The Complete Novels', 'Arthur Conan Doyle', 1887, 'LIT-58'),
('Dracula', 'Bram Stoker', 1897, 'LIT-59'),
('Frankenstein', 'Mary Shelley', 1818, 'LIT-60');